/// <reference types="vite/client" />
VITE_SUPABASE_URL=https://kgjmuvumoqthewnbzfig.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnam11dnVtb3F0aGV3bmJ6ZmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NDAzNzgsImV4cCI6MjA1MDMxNjM3OH0.BJI4mLgOZlZ_tTJCZSmj510VpkK7zUfs7x6xBNvWcT8